name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Verify Build Output
      run: |
        echo "Verificando conteúdo do diretório de build:"
        ls -R FiapGrupo57Fase2.WebAPI/bin/Release/
        ls -R FiapGrupo57Fase2.WebAPI/obj/Release/

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          FiapGrupo57Fase2.WebAPI/bin/Release/
          FiapGrupo57Fase2.WebAPI/obj/Release/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: .

    - name: Verify Downloaded Artifacts
      run: |
        echo "Verificando conteúdo dos artefatos baixados:"
        ls -R .

    - name: Run all tests
      run: dotnet test FiapGrupo57Fase2.Test/FiapGrupo57Fase2.Test.csproj --no-build --verbosity normal --logger "trx;LogFileName=FiapGrupo57Fase2.Test/TestResults/all-test-results.trx"

    - name: List Test Results
      run: |
        echo "Verificando conteúdo do diretório TestResults:"
        ls FiapGrupo57Fase2.Test/TestResults

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: FiapGrupo57Fase2.Test/TestResults

  setup-monitoring:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Setup Prometheus
      run: docker run -d --name prometheus -p 9090:9090 prom/prometheus

    - name: Setup Grafana
      run: docker run -d --name grafana -p 3000:3000 grafana/grafana

    - name: Wait for Grafana to start 
      run: sleep 30

    - name: Verify Prometheus 
      run: |
        echo "Verificando se Prometheus está em execução:"
        docker ps -a
        curl -f http://localhost:9090/metrics || exit 1

    - name: Verify Grafana
      run: |
        echo "Verificando se Grafana está em execução:"
        docker ps -a
        curl -L -f http://localhost:3000 > /dev/null || exit 1

    - name: Grafana Error Logs
      if: failure()
      run: docker logs grafana
