name: .NET CI Pipeline with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Test with Docker
      run: |
        docker build -t myapp:latest .
        docker run --rm myapp:latest

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults

  setup-monitoring:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Setup Prometheus
      run: docker run -d --name prometheus -p 9090:9090 prom/prometheus

    - name: Setup Grafana
      run: docker run -d --name grafana -p 3000:3000 grafana/grafana

    - name: Wait for Grafana to start 
      run: sleep 30

    - name: Verify Prometheus 
      run: |
        echo "Verificando se Prometheus está em execução:"
        docker ps -a
        curl -f http://localhost:9090/metrics || exit 1

    - name: Verify Grafana
      run: |
        echo "Verificando se Grafana está em execução:"
        docker ps -a
        curl -L -f http://localhost:3000 > /dev/null || exit 1

    - name: Grafana Error Logs
      if: failure()
      run: docker logs grafana